### PR TITLE
REST-API Query Refactor (UA-695)

### PR DESCRIPTION
**Pull request by kotodharma**
This stuff needs to be done in rails console:
```
Geography.create(universe: 'DBEDT', fips: '15', display_name: 'State of Hawaii', display_name_short: 'State of Hawaii', handle: 'HI')
Geography.create(universe: 'DBEDT', fips: '15001', display_name: 'Hawaii County', display_name_short: 'Hawaii County', handle: 'HAW')
Geography.create(universe: 'DBEDT', fips: '15003', display_name: 'City and County of Honolulu', display_name_short: 'Honolulu County', handle: 'HON')
Geography.create(universe: 'DBEDT', fips: '15007', display_name: 'Kauai County', display_name_short: 'Kauai County', handle: 'KAU')
Geography.create(universe: 'DBEDT', fips: '15009', display_name: 'Maui County', display_name_short: 'Maui County', handle: 'MAU')
```
Then, this needs to be done in db:
```
update series s
  join geographies g on s.universe = g.universe
                    and g.handle = substring_index(substring_index(s.name, '@', -1), '.', 1)
set s.geography_id = g.id
where s.geography_id is null
```
 
## Testing
Find routes in `routers/search.go` and try each one with different params filled in.
Note that there is no route for a URL such as `/v1/search/series?q=&geo=&freq=&u=`. Wrong results will be returned if you call such an endpoint.

### CODE REVIEW

**Comment by jonpage** [comment]
I'm not sure what you mean by "wrong" results. I get a 404, which is the correct response for `/v1/search/series?q=&geo=&freq=&u=`.

**Comment by kotodharma** [comment]
Sorry - what I meant was not what happens when you call that URL exactly like that, but if you fill in the params. So, something like `/v1/search/series?q=pine&geo=MAU&freq=Q&u=DBEDT` will return results for UHERO series rather than DBEDT series, because that exact combination of parameters does not have a route for it. However if you take this same query string and add `&expand=true` to the end, now you have something with a route, and you get DBEDT results. Could easily be fixed, of course, just by adding the route. Shall I create the story, or is this a known "gap" in functionality that is supposed to be that way for some reason?

**Comment by jonpage** [comment]
Yes, we should create a story for this.
The next step should be to see what our current exposure is. That is, does the DBEDT data warehouse or the Data Portal use the query in question. If the endpoint is in use, we need to plug that gap ASAP.

**Comment by kotodharma** [comment]
For more on testing, see the next PR, for UA-727.

**Comment by kotodharma** [comment]
OK... whew... I was trying to make it so that we could test and deploy this and 727 together, but then testing the latter is turning out to be a real hassle, so I backed off and decided "let's get 695 out the door asap". I've retested now with all three portals and it looks good. Please try again.

**Pull request merged**
